#!/bin/bash
#$ -S /bin/bash
#$ -cwd
#$ -V

# set up the proper environment variables for a PBS job.
#PBS -V
#PBS -o stdout.log
#PBS -e stderr.log
##PBS -o /dev/null
##PBS -e /dev/null
#PBS -l mem=5gb

if [ ${HOSTNAME} == "tim.selfip.org" ]; then
 # go to directory from which job was submitted.  If this job is being run
 # (not submitted to a queue) this should not run.
 if [ ! -z ${PBS_O_WORKDIR} ]; then
  echo "going to PBS working directory: ${PBS_O_WORKDIR}"
  cd ${PBS_O_WORKDIR}
 fi
fi

# Function for formatted echo
function fecho {
 echo "### ${1}"
}

## INPUT PARAMETERS ##
. ./ins/parameters.in

function compile {
## COMPILE ##
 fecho "$(date) compiling dynamix.cpp..."
 CPP=g++
 # check if better compilers are installed
 which g++-4.7.0 &> /dev/null
 if [ $? == 0 ] ; then CPP=g++-4.7.0 ; fi
 which g++-4.7.1 &> /dev/null
 if [ $? == 0 ] ; then CPP=g++-4.7.1 ; fi
 which g++-4.7.2 &> /dev/null
 if [ $? == 0 ] ; then CPP=g++-4.7.2 ; fi
 which icpc &> /dev/null
 if [ $? == 0 ] ; then CPP=icpc ; fi
 cd build
 make -j 12 CPP=$CPP
 if [ $? == 0 ] ; then
  fecho "$(date) done compiling!" && make install
  cd ..
 else
  fecho "$(date) failed to compile :("
  exit
 fi
}

function run {
## RUN THE PROGRAM! ##
 module load intel
 module load cvode/2.7.0
 fecho "$(date) running dynamix..."
 ./bin/dynamix
 if [ $? == 0 ] ; then
  fecho "$(date) dynamix done!"
 else
  fecho "$(date) dynamix did not run :("
  exit
 fi
 # move outputs
 [ -d outs ] && rm -rf outs
 mkdir -p outs
 mv *.out outs/
 # move plot files
 [ -d figures ] && rm -rf figures
 mkdir -p figures
 chmod 755 *.plt
 mv *.plt figures/
}

function backup {
## BACK UP FILES ##
 fecho "$(date) backing things up..."
 durr=backup/dynamix_$(date +%F.%H.%M.%S)
 mkdir -p $durr
 cp -rf ins/ outs/ bin/ figures/ doc/ total_dynamix $durr
 [ $do_plot == 1 ] && cp *.eps $durr
 [ $do_movie == 1 ] && cp bulk_states.avi $durr
 [ $(($Nb)) == 0 ] && rm -f $durr/outs/tbprob.out $durr/outs/Ibprob.out $durr/outs/bmax.out && ls $durr
 fecho "$(date) all backed up\!"
}

function plot {
 if [ -d figures ]; then
  for plotfile in $(ls figures/*plt)
  do
   fecho "plotting ${plotfile}..."
   ./$plotfile
  done
 else
  fecho "Nothing to plot."
 fi
}

### This is where the script actually starts doing things. ###

fecho "$(date) dynamix run starting now..."
fecho ""
fecho ""

[ $do_compile == 1 ] && compile
[ $do_run == 1 ] && run
[ $do_plot == 1 ] && plot
[ $do_backup == 1 ] && backup

fecho "$(date) all done!"
fecho ""
fecho ""
